name: chipln
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
  adv_fab: ^1.0.5
  animations: ^2.0.0
  bloc: ^7.0.0
  bottom_bar_page_transition: ^2.0.0
  circular_profile_avatar: ^2.0.0
  csc_picker: ^0.2.5
  cupertino_icons: ^1.0.3
  dropdown_below: ^0.0.7
  equatable: ^2.0.2
  eva_icons_flutter: ^3.0.0
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  flexible_scrollbar: ^0.1.2
  flutter_bloc: ^7.0.0
  flutter_form_builder: ^6.0.1
  flutter_snake_navigationbar: ^0.5.0
  flutter_xlider: ^3.4.0
  glassmorphism: ^2.0.1
  google_fonts: ^2.0.0
  image_picker_gallery_camera: ^0.2.2
  intl: ^0.17.0
  logger: ^1.0.0
  progress_state_button: ^1.0.3
  seafarer: ^0.1.0
  sizer: ^2.0.13
  smooth_page_indicator: ^0.2.3

dependency_overrides:
  last_state: ^0.1.1
  international_phone_field: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_gen_runner: null

  very_good_analysis: ^2.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/startup/
    - assets/images/login/
    - assets/images/home/
    - assets/images/company/
    - assets/animation/
flutter_gen:
  output: lib/presentation/global/assets

  # Optional
  integrations:
    flutter_svg: true
